[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "colored_networks"
version = "0.0.1"
dependencies = [
    "networkx",
    "matplotlib",
    "ipykernel",
]