name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Run pytest
        run: python -m pytest tests/
